//+build generate

package main

import (
	// "github.com/zserge/lorca"
	"io/ioutil"
	"os"
	"fmt"
)

var indexTemplate = `// Code generated by Wizard. DO NOT EDIT.
package api

func IndexFile() string {
	return ` + "`%s`" + `
}
`

func main() {
	// lorca.Embed("api", "../api/assets.go", "../dashboard/dist")
	indexFile, err := ioutil.ReadFile("../../dashboard/index_prod.html")
	if err != nil {
		panic(err)
	}

	destContent := []byte(fmt.Sprintf(indexTemplate, string(indexFile)))
	if err := ioutil.WriteFile("../../api/index.go", destContent, os.ModePerm); err != nil {
		panic(err)
	}
}
